{
  "openapi": "3.0.0",
  "info": {
    "title": "Thre.ls Task",
    "contact": {},
    "version": "1.0-oas3"
  },
  "servers": [
    {
      "url": "http://threls.elza3ym.net/api"
    }
  ],
  "tags": [
    {
      "name": "Authentication"
    },
    {
      "name": "Products"
    },
    {
      "name": "Orders"
    }
  ],
  "paths": {
    "/auth/login": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Login",
        "operationId": "Login",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/auth_login_body"
              },
              "example": {
                "email": "admin@admin.com",
                "password": "admin1234"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": ""
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/auth/register": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Register",
        "operationId": "Register",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/auth_register_body"
              },
              "example": {
                "email": "admin1@admin.com",
                "password": "admin1234",
                "password_confirmation": "admin1234",
                "name": "Mohamed"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": ""
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/user": {
      "get": {
        "tags": [
          "Authentication"
        ],
        "summary": "Get User Info",
        "operationId": "GetUserInfo",
        "parameters": [],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/auth/logout": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Logout",
        "operationId": "Logout",
        "parameters": [],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/products": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "List Products ( Paginate )",
        "operationId": "ListProducts(Paginate)",
        "parameters": [],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/products/108334/show": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Get Product",
        "operationId": "GetProduct",
        "parameters": [],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/products/import": {
      "post": {
        "tags": [
          "Products"
        ],
        "summary": "Import CSV Products Copy",
        "operationId": "ImportCSVProductsCopy",
        "parameters": [],
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "$ref": "#/components/schemas/products_import_body"
              },
              "encoding": {}
            }
          },
          "required": false
        },
        "responses": {
          "200": {
            "description": ""
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/products/update-cart": {
      "post": {
        "tags": [
          "Products"
        ],
        "summary": "Add To Cart",
        "operationId": "AddToCart",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/products_updatecart_body"
              },
              "example": {
                "items": [
                  {
                    "product_id": 108334,
                    "amount": 1
                  },
                  {
                    "product_id": 108334,
                    "amount": 1532
                  }
                ]
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": ""
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/order": {
      "post": {
        "tags": [
          "Orders"
        ],
        "summary": "Place Order",
        "operationId": "PlaceOrder",
        "parameters": [],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "deprecated": false,
        "security": [
          {
            "bearer": []
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "LoginRequest": {
        "title": "LoginRequest",
        "required": [
          "email",
          "password"
        ],
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "example": {
          "email": "admin@admin.com",
          "password": "admin1234"
        }
      },
      "RegisterRequest": {
        "title": "RegisterRequest",
        "required": [
          "email",
          "name",
          "password",
          "password_confirmation"
        ],
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "password_confirmation": {
            "type": "string"
          },
          "name": {
            "type": "string"
          }
        },
        "example": {
          "email": "admin1@admin.com",
          "password": "admin1234",
          "password_confirmation": "admin1234",
          "name": "Mohamed"
        }
      },
      "AddToCartRequest": {
        "title": "AddToCartRequest",
        "required": [
          "items"
        ],
        "type": "object",
        "properties": {
          "items": {
            "type": "array",
            "description": "",
            "items": {
              "$ref": "#/components/schemas/Item"
            }
          }
        },
        "example": {
          "items": [
            {
              "product_id": 108334,
              "amount": 1
            },
            {
              "product_id": 108334,
              "amount": 1532
            }
          ]
        }
      },
      "Item": {
        "title": "Item",
        "required": [
          "amount",
          "product_id"
        ],
        "type": "object",
        "properties": {
          "product_id": {
            "type": "integer",
            "format": "int32"
          },
          "amount": {
            "type": "integer",
            "format": "int32"
          }
        },
        "example": {
          "product_id": 108334,
          "amount": 1
        }
      },
      "auth_login_body": {
        "allOf": [
          {
            "$ref": "#/components/schemas/LoginRequest"
          },
          {
            "example": {
              "email": "admin@admin.com",
              "password": "admin1234"
            }
          }
        ]
      },
      "auth_register_body": {
        "allOf": [
          {
            "$ref": "#/components/schemas/RegisterRequest"
          },
          {
            "example": {
              "email": "admin1@admin.com",
              "password": "admin1234",
              "password_confirmation": "admin1234",
              "name": "Mohamed"
            }
          }
        ]
      },
      "products_import_body": {
        "required": [
          "file"
        ],
        "type": "object",
        "properties": {
          "file": {
            "type": "string"
          }
        }
      },
      "products_updatecart_body": {
        "allOf": [
          {
            "$ref": "#/components/schemas/AddToCartRequest"
          },
          {
            "example": {
              "items": [
                {
                  "product_id": 108334,
                  "amount": 1
                },
                {
                  "product_id": 108334,
                  "amount": 1532
                }
              ]
            }
          }
        ]
      }
    },
    "securitySchemes": {
      "bearer": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  }
}
